name: Developer Hub
markdown: redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data",  "no_intra_emphasis", "fenced_code_blocks"]

highlighter: pygments
safe: true
baseurl: /developers
exclude: ['.ruby-version', 'node_modules', 'package.json', 'bower.json']
sass:
  sass_dir: static/_sass

# Blog/Post configuration
paginate: 5
paginate_path: "blog/page:num"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      organization-name: "vehicle-history.io"
      organization-url: "https://vehicle-history.io"
      organization-email: zenedith@wp.pl
      site-name: /developers
      source-code-policy.url: "https://github.com/vehicle-history"
